### ISSUE TITLE
keywordCloud plugin makes the canvas blocker of Firefox to stop javascript execution

### ISSUE THREAD

**Issue by kaluosi** [lepidus/ojs3-keywordcloud-plugin#10]
After installing and activating keywordCloud plugin the OJS 3 page in Firefox 85 issues a warning that javascript execution is slow because canvas blocker is causing it.

**Comment by diegoabadan** [comment]
Thank you @kaluosi 

Our team will check the reported problem and soon we hope to give you feedback.

**Comment by thiagolepidus** [comment]
Hello @kaluosi!

The warning appears to be related to the Canvas Blocker extension.

Disabling the extension does the warning continue to appear?

**Comment by kaluosi** [comment]
Thanks thiagolepidus:
At first I thought it could be a extension but it seems the plugin works properly as in:
http://emerita.revistas.csic.es/index.php/emerita
It does not work in:
http://revista.sel.edu.es
here the plugin appears with only two words of the first article (there are more than 500 articles) an keeps waiting for ??
This happens with different browsers, so I think it is not related with a browser extension

**Comment by diegoabadan** [comment]
Hola @kaluosi 

Aún no hemos podido identificar algo que explique el problema reportado con la segunda revista. ¿Sería posible activar temporalmente el complemento para que podamos intentar identificar algo?

Si es posible, utilice la última versión disponible en: https://github.com/lepidus/keywordCloud/releases/

Gracias

----

Hello @kaluosi 

We have not yet been able to identify something that explains the problem reported with the second magazine. Would it be possible to temporarily activate the plugin so that we can try to identify something?

If possible, use the latest version available at: https://github.com/lepidus/keywordCloud/releases/

Thanks

**Comment by diegoabadan** [comment]
We have a new version of the plugin:
https://github.com/lepidus/keywordCloud/releases

Please, if the problem persists, reopen this issue.
